(function() {var implementors = {};
implementors['openssl'] = ["<a class='stability Unmarked' title='No stability level'></a>impl&lt;S: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Stream.html' title='std::io::Stream'>Stream</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='openssl/ssl/struct.SslStream.html' title='openssl::ssl::SslStream'>SslStream</a>&lt;S&gt;",];
implementors['http'] = ["<a class='stability Unmarked' title='No stability level'></a>impl&lt;T: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='http/buffer/struct.BufferedStream.html' title='http::buffer::BufferedStream'>BufferedStream</a>&lt;T&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;S: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> + <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> + <a class='trait' href='http/connecter/trait.Connecter.html' title='http::connecter::Connecter'>Connecter</a> = <a class='type' href='http/client/type.NetworkStream.html' title='http::client::NetworkStream'>NetworkStream</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='http/client/request/struct.RequestWriter.html' title='http::client::request::RequestWriter'>RequestWriter</a>&lt;S&gt;","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='type' href='http/client/type.NetworkStream.html' title='http::client::NetworkStream'>NetworkStream</a>","<a class='stability Unmarked' title='No stability level'></a>impl&lt;'a&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='http/server/response/struct.ResponseWriter.html' title='http::server::response::ResponseWriter'>ResponseWriter</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
