(function() {var implementors = {};
implementors['heliotrope'] = ["<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Show.html' title='core::fmt::Show'>Show</a> for <a class='enum' href='heliotrope/enum.SolrValue.html' title='heliotrope::SolrValue'>SolrValue</a>","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Show.html' title='core::fmt::Show'>Show</a> for <a class='struct' href='heliotrope/struct.SolrField.html' title='heliotrope::SolrField'>SolrField</a>","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Show.html' title='core::fmt::Show'>Show</a> for <a class='struct' href='heliotrope/struct.SolrDocument.html' title='heliotrope::SolrDocument'>SolrDocument</a>","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Show.html' title='core::fmt::Show'>Show</a> for <a class='struct' href='heliotrope/struct.SolrDeleteRequest.html' title='heliotrope::SolrDeleteRequest'>SolrDeleteRequest</a>","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Show.html' title='core::fmt::Show'>Show</a> for <a class='struct' href='heliotrope/struct.SolrUpdateResponse.html' title='heliotrope::SolrUpdateResponse'>SolrUpdateResponse</a>","<a class='stability Unmarked' title='No stability level'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Show.html' title='core::fmt::Show'>Show</a> for <a class='struct' href='heliotrope/struct.SolrQueryResponse.html' title='heliotrope::SolrQueryResponse'>SolrQueryResponse</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
